export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';


export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USER_FAIL = 'LOAD_USER_FAIL';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT = 'LOGOUT';
export const DELETE_PROFILE_LOGOUT = 'DELETE_PROFILE_LOGOUT';

export const PROFILE_FETCH_START = 'PROFILE_FETCH_START';
export const PROFILE_FETCH_FAIL = 'PROFILE_FETCH_FAIL';
export const PROFILE_FETCH_SUCCESS = 'PROFILE_FETCH_SUCCESS';

export const GET_ALL_PROFILES_START = 'GET_ALL_PROFILES_START';
export const GET_ALL_PROFILES_FAIL = 'GET_ALL_PROFILES_FAIL';
export const GET_ALL_PROFILES_SUCCESS = 'GET_ALL_PROFILES_SUCCESS';

export const GET_PROFILE_BY_ID_START = 'GET_PROFILE_BY_ID_START';
export const GET_PROFILE_BY_ID_FAIL = 'GET_PROFILE_BY_ID_FAIL';
export const GET_PROFILE_BY_ID_SUCCESS = 'GET_PROFILE_BY_ID_SUCCESS';

export const GET_REPOS_BY_USERNAME_START = 'GET_REPOS_BY_USERNAME_START';
export const GET_REPOS_BY_USERNAME_FAIL = 'GET_REPOS_BY_USERNAME_FAIL';
export const GET_REPOS_BY_USERNAME_SUCCESS = 'GET_REPOS_BY_USERNAME_SUCCESS';


export const PROFILE_CREATE_START = 'PROFILE_CREATE_START';
export const PROFILE_CREATE_FAIL = 'PROFILE_CREATE_FAIL';
export const PROFILE_CREATE_SUCCESS = 'PROFILE_CREATE_SUCCESS';

export const ADD_EXPERIENCE_PROFILE_START = 'ADD_EXPERIENCE_PROFILE_START';
export const ADD_EXPERIENCE_PROFILE_FAIL = 'ADD_EXPERIENCE_PROFILE_FAIL';
export const ADD_EXPERIENCE_PROFILE_SUCCESS = 'ADD_EXPERIENCE_PROFILE_SUCCESS';

export const ADD_EDUCATION_PROFILE_START = 'ADD_EDUCATION_PROFILE_START';
export const ADD_EDUCATION_PROFILE_FAIL = 'ADD_EDUCATION_PROFILE_FAIL';
export const ADD_EDUCATION_PROFILE_SUCCESS = 'ADD_EDUCATION_PROFILE_SUCCESS';

export const DELETE_EDUCATION_FAIL = 'DELETE_EDUCATION_FAIL'; 
export const DELETE_EDUCATION_SUCCESS = 'DELETE_EDUCATION_SUCCESS'; 

export const DELETE_EXPERIENCE_FAIL = 'DELETE_EXPERIENCE_FAIL'; 
export const DELETE_EXPERIENCE_SUCCESS = 'DELETE_EXPERIENCE_SUCCESS'; 

export const DELETE_ACCOUNT_SUCCESS = 'DELETE_ACCOUNT_SUCCESS';
export const DELETE_ACCOUNT_FAIL = 'DELETE_ACCOUNT_FAIL';

export const GET_ALL_POSTS_SUCCESS = 'GET_ALL_POSTS_SUCCESS';
export const GET_ALL_POSTS_FAIL = 'GET_ALL_POSTS_FAIL';  

export const GET_SINGLE_POST_SUCCESS = 'GET_SINGLE_POST_SUCCESS';
export const GET_SINGLE_POST_FAIL = 'GET_SINGLE_POST_FAIL';

export const LIKE_A_POST_SUCCESS = 'LIKA_A_POST_SUCCESS';

export const UNLIKE_POST_SUCCESS = 'UNLIKE_POST_SUCCESS';

export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL';

export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';

export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';

export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS'; 





